### ISSUE TITLE
Error: Blob auditing can be configured on primary databases only

### ISSUE THREAD

**Issue by gsgill76** [klagan/tf-sql-server-with-failover#1]
provider.azurerm: version = "~> 2.3"
getting the error when creating the secondary database (my_database2).
Here is the log:

`module.my_sql_server_failover_example.azurerm_resource_group.my_resource_group[1]: Creating...
module.my_sql_server_failover_example.azurerm_resource_group.my_resource_group[0]: Creating...
module.my_sql_server_failover_example.azurerm_resource_group.my_resource_group[0]: Creation complete after 5s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus]
module.my_sql_server_failover_example.azurerm_resource_group.my_resource_group[1]: Creation complete after 5s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-02-westus]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Creating...
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Creating...
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Still creating... [50s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Still creating... [50s elapsed]
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[1]: Creation complete after 58s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-02-westus/providers/Microsoft.Sql/servers/gs19-02-westus]
module.my_sql_server_failover_example.module.my_sql_server_2_firewall_rules.azurerm_sql_firewall_rule.all_azure_services_sqlserver_rule: Creating...
module.my_sql_server_failover_example.azurerm_sql_server.my_sql_server[0]: Creation complete after 59s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus/providers/Microsoft.Sql/servers/gs19-01-eastus]
module.my_sql_server_failover_example.module.my_sql_server_1_firewall_rules.azurerm_sql_firewall_rule.all_azure_services_sqlserver_rule: Creating...
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Creating...
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Creating...
module.my_sql_server_failover_example.module.my_sql_server_2_firewall_rules.azurerm_sql_firewall_rule.all_azure_services_sqlserver_rule: Creation complete after 5s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-02-westus/providers/Microsoft.Sql/servers/gs19-02-westus/firewallRules/AllowAzureServices]
module.my_sql_server_failover_example.module.my_sql_server_1_firewall_rules.azurerm_sql_firewall_rule.all_azure_services_sqlserver_rule: Creation complete after 4s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus/providers/Microsoft.Sql/servers/gs19-01-eastus/firewallRules/AllowAzureServices]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[0]: Creation complete after 41s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus/providers/Microsoft.Sql/servers/gs19-01-eastus/elasticPools/gs19-ep]
module.my_sql_server_failover_example.azurerm_mssql_elasticpool.my_elastic_pool[1]: Creation complete after 43s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-02-westus/providers/Microsoft.Sql/servers/gs19-02-westus/elasticPools/gs19-ep]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Creating...
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [50s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [1m0s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Still creating... [1m10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_database.my_database: Creation complete after 1m15s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus/providers/Microsoft.Sql/servers/gs19-01-eastus/databases/gillsdb]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Creating...
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [20s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [30s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [40s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [50s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [1m0s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [1m10s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Still creating... [1m20s elapsed]
module.my_sql_server_failover_example.azurerm_sql_failover_group.my_failover_group: Creation complete after 1m27s [id=/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/gs19-01-eastus/providers/Microsoft.Sql/servers/gs19-01-eastus/failoverGroups/gs19]
module.my_sql_server_failover_example.azurerm_sql_database.my_database2: Creating...
module.my_sql_server_failover_example.azurerm_sql_database.my_database2: Still creating... [10s elapsed]

Error: Error issuing create/update request for SQL Database "gillsdb" Blob Auditing Policies(SQL Server "gs19-02-westus"/ Resource Group "gs19-02-westus"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."

  on tf-sql-server-with-failover\main.tf line 59, in resource "azurerm_sql_database" "my_database2":
  59: resource "azurerm_sql_database" "my_database2" {
`

**Comment by klagan** [comment]
Hi,  Im still learning this tuff myself, but I noticed that the erro message is about am extended database blob auditing policy that has been set on the primary database but it not possible for mirrored database.
Have you changed something in the script?  Have you tried - and does it work - without modification?  If true, then at least we know what we are dealing with as I believe the vanilla script works as I have used it.

**Comment by klagan** [comment]
Something i did notice though.  I havent tested these scripts with the new terraform providers.  I wrote these before th enew providers came out and havent had a chance to revise them.  
Try adding a `version.tf` file with something like the following in it:
```
terraform {
  required_version = ">= 0.12"
}

provider "azurerm" {
  version = "~> 1.44"
}
```

**Comment by gsgill76** [comment]
I tried with provider.azurerm: version = "~> 2.0.0", the script worked well with no error. looks like 2.3.0 some new properties are added that need code modification, I am also in the search of that. will keep you posted in case found anything.
